// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package productrepository

import (
	"database/sql"
)

type Category struct {
	ID   int64
	Name string
}

type Product struct {
	ID         int64
	Name       sql.NullString
	ImgUrl     sql.NullString
	Price      sql.NullInt32
	Stock      sql.NullInt32
	CategoryID sql.NullInt32
}
