// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"
)

type User struct {
	ID         int64
	Name       string
	Email      string
	Password   string
	IsAdmin    sql.NullBool
	IsVerified sql.NullBool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
